[profile.default]
src = "script"
out = "out"
libs = ["lib"]
solc = "0.8.36"
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "../" }]
allow_paths = ["../"]
remappings = [
  "duck-launcher-contracts/=../duck-launcher/",
  "duckraise-contracts/=../duckraise/",
  "duck-incubation-contracts/=../duck-incubation/",
  "common-contracts/=../common/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
ink = "${INK_RPC_URL}"
